### ISSUE TITLE
Bikeshedding new Barrel.toml

### ISSUE THREAD

**Issue by revol-xut** [lf-lang/lingo#3]
## Proposal of Barrel.toml
```toml
[package]
name = "example_project"
version = "0.1.0"
authors = ["tassilo.tannerber@tu-dresden.de"]
homepage = "https://lf-lang.org"
license = "Weird Stallman License"
description = "A little Barrel.toml so people can discuss it"

# shared properties of all binaries
[properties]
fast = true

# first binary in the project
[[app]]
name = "git-hook" # <-- should this default to package.name ?
target = "cpp"
# main_reactor defaults to src/main.lf

# dependencies
[[app.dependencies]]
git = "0.3.2"
tarfetcher = "0.4.2"

# replacement for target properties
[[app.properties]]
cmake-include = "./my-cmake.cmake"
logging = true

# second binary
[[app]]
name = "embedded"
main_reactor = "src/EmbeddedMain.lf"
target = "zephyre"

# [CONTROVERSIAL] AND NOT PART OF THE PROPOSAL
# for projects that are way to complicated to build ourself
# build-script = "./build.sh"
# 
# build-script-inline = '''
# 	barrel generate --out ./src-gen
# 	mkdir build
# 	cd build
# 	cmake ../src-gen
# 	make
# '''

[[app.dependencies]]
blink = "0.1.2"

[[app.properties]]
no-compile = true
```
